import { Star as StarIcon, History, ChevronRight, ArrowUp, BookOpen, Box, Building, ChartNoAxesCombined, CreditCard, Database, ExternalLink, FileChartColumn, FileCheck, GraduationCap, Inbox, LogOut, Mail, RotateCcw, Search, ShieldCheck, SlidersHorizontal, Sparkles, UserRound, UsersRound, X } from 'lucide-react';
const menus = [['예산',FileChartColumn],['자금',Database],['집행',CreditCard],['원장',BookOpen],['결산',FileCheck],['수입',ChartNoAxesCombined],['급여',Mail],['인사',UsersRound],['자산',Box],['자율통제',ShieldCheck],['시설물',Building],['자료모아',Inbox],['공통',SlidersHorizontal]] as const;
const actions = [['품의 베껴 쓰기','지난 품의를 골라 새로 만듭니다'],['지출결의 올리기','품의를 골라 결의를 채웁니다'],['카드내역으로 결의','승인내역을 결의 줄로 채웁니다'],['예산변경 재원 찾기','어디서 끌어올지 후보를 냅니다']];
const requests = [['2027년 지출예산 편성요구 수집','2일 남음',4,21],['[QA-DTC-20260926-1500] 다부서 표수집 1009','3일 남음',2,2],['[QA-DTC-20260926-1500] 다부서 표수집 1003','3일 남음',0,2],['[QA-DTC-20260926-1500] 개인설문요청 1055','3일 남음',0,1],['[QA-DTC-20260926-1500] 기명설문요청 1055','3일 남음',2,2],['[QA-DTC-20260926-1500] 익명설문요청 1055','3일 남음',2,2],['[QA-DTC-20260926-1500] 다부서 표수집 1017','3일 남음',2,2],['[QA-DTC-20260926-1500] 다부서 표수집 1024','8일 남음',0,2]] as const;
const questions = ['올해 예산 얼마야?','인사노무팀 예산은?','예산 많은 사업 5개 보여줘','올해 얼마나 썼어?','국민체육센터 집행률은?','지난달 품의 다시 올려줘'];
function Star(){return <Sparkles className="magic-star" size={17} fill="#ffec00" strokeWidth={2} aria-hidden="true"/>}
function Progress({value,green=false}:{value:number;green?:boolean}){return <div className={`progress ${green?'green':''}`}><span style={{width:`${value}%`}}/></div>}
export default function Home(){return <div className="app-shell">
<header className="topbar"><div className="company-logo"><span className="company-symbol" aria-hidden="true"><i/><i/><i/><i/><i/><i/></span><div><strong>의왕도시공사</strong><small>Uiwang Urban Corporation</small></div></div><div className="topbar-main"><h1><em>AI</em>재정정보시스템</h1><div className="search-box"><Search size={17}/><span>화면 이름으로 찾기</span></div><div className="account"><button className="ai-shortcut"><Star/>AI 재정박사</button><button><UserRound size={17}/><b>관리자</b></button><span className="account-divider"/><button className="logout"><LogOut size={16}/>로그아웃</button></div></div></header>
<aside className="sidebar"><div className="quick-menu"><div className="quick-title"><StarIcon className="favorite-star" size={15} fill="currentColor" aria-hidden="true"/><b>즐겨찾기</b><small>전체<ChevronRight size={11} aria-hidden="true"/></small></div><p className="quick-hint">메뉴의 <StarIcon size={11} aria-hidden="true"/> 로 담기</p><div className="quick-title"><History className="recent-icon" size={14} aria-hidden="true"/><b>자주 쓰는</b><small>전체<ChevronRight size={11} aria-hidden="true"/></small></div><div className="quick-links"><span>품의</span><span>서식함</span><span>원인행위</span></div></div><nav aria-label="주 메뉴">{menus.map(([name,Icon])=><button key={name}><Icon size={20} strokeWidth={2}/><span>{name}</span></button>)}</nav></aside>
<div className="workspace"><div className="tabbar"><button><ExternalLink size={15}/>새창</button><span/><button><X size={16}/>전체 닫기</button></div><main className="dashboard"><div className="dashboard-left">
<section className="briefing"><header><div><Star/><h2>오늘의 브리핑</h2></div><span>9월 30일 기준</span></header><ul><li><b>2026 회계연도</b> 지출결의가 <b>0원</b>으로 예산현액 999억원의 <b>0.0%</b>입니다. 남은 예산은 999억원입니다.</li><li>자료 제출 마감이 7일 안으로 다가온 요청이 <b>7건</b> 있습니다. 가장 급한 것은 '2027년 지출예산 편성요구 수집'로 <b>2일</b> 남았습니다.</li><li>아직 자료를 내지 않은 곳이 <b>20곳</b>입니다(전체 34곳).</li></ul></section>
<section className="ai-actions"><header><Star/><h2>AI가 대신해 드립니다</h2><span>누르면 재정박사가 그 일부터 시작합니다</span></header><div className="action-grid">{actions.map(([title,description])=><button key={title}><b>{title}</b><span>{description}</span></button>)}</div></section>
<section className="metrics" aria-label="재정 요약"><article><h3>예산 집행률</h3><strong>0.0%</strong><Progress value={0}/><p>지출결의 0 / 현액 999억</p></article><article><h3>지급 대기</h3><strong className="red">0</strong><p className="metric-note">0건 · 지급명령 전</p></article><article><h3>자료 제출률</h3><strong>41.2%</strong><Progress value={41.2}/><p>14 / 34곳 제출</p></article><article><h3>마감 임박</h3><strong className="red">7건</strong><p className="metric-note">집계 중 8건 중 7일 안</p></article></section>
<div className="bottom-grid"><section className="data-panel"><header><h2>자료모아 · 집계 중인 수집 요청</h2><button>수집 요청 열기</button></header><div className="table-head"><span>자료명</span><span>남은 기간</span><span>제출 진행</span></div><div className="table-scroll"><table><colgroup><col className="name-col"/><col className="due-col"/><col className="submission-col"/></colgroup><tbody>{requests.map(([name,due,done,total])=><tr key={name}><td>{name}</td><td className="due">{due}</td><td><div className="row-progress"><Progress value={done/total*100} green={done===total}/><span>{done} / {total}</span></div></td></tr>)}</tbody></table></div></section><section className="data-panel organization"><header><h2>조직별 집행 현황</h2><span>지출결의액이 큰 차례</span></header><p>집행 자료가 없습니다.</p></section></div></div>
<aside className="chat-panel"><header className="chat-header"><span className="graduate"><GraduationCap size={22}/></span><div><div className="chat-title"><h2>AI 재정박사</h2><span>BETA</span></div><p><i/>예산·집행 자료로 바로 답해요</p></div><button className="reset" aria-label="대화 초기화"><RotateCcw size={16}/></button></header><div className="chat-body"><div className="chat-sparkle"><Sparkles size={18} strokeWidth={2}/></div><h3>무엇을 찾아 드릴까요?</h3><p>부서나 사업 이름을 넣어 물어보세요. 시스템 자료로만 답합니다.</p><h4>이렇게 물어보세요</h4><div className="questions">{questions.map(q=><button key={q}>{q}</button>)}</div></div><footer className="chat-footer"><div className="chat-compose"><div>예) 우리 부서 올해 예산 얼마야?</div><button aria-label="메시지 보내기"><ArrowUp size={21}/></button></div><p>예산현액·지출결의 기준 · 내 조직권한 범위</p></footer></aside></main></div></div>}
